package paymentsys;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

import java.awt.Dimension;
import java.awt.HeadlessException;
import java.awt.Toolkit;
import javax.swing.JOptionPane;
import java.sql.*;
import java.text.DateFormat;
import java.text.SimpleDateFormat;
/**
 *
 * @author Wiktor
 */
public class PaymentsystemPoland extends javax.swing.JFrame {
   
    double PensjaPodstawowa;
    double DodDojazdowy;
    double PremiaProdukcyjna;
    double OplataZywieniowa;
    double LacznyPodatek;
    double SummPension;
    
    Connection con_emp_list = null;
    PreparedStatement prepstat = null;
    ResultSet resSet = null; 
    
    Connection con_user_data = null;
    PreparedStatement pstmt = null;
    
    
    
    
    
    /**
     * Creates new form Paymentsystem
     */
    public PaymentsystemPoland() {
        initComponents();
        
        Toolkit toolkit = getToolkit();
        Dimension size = toolkit.getScreenSize();
        setLocation(size.width/2 - getWidth()/2, size.height/2 - getHeight()/2);
        
        this.fillCombo();
        
    }
    
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jEmployeeNameLabel3 = new javax.swing.JLabel();
        jPensjaLbl = new javax.swing.JLabel();
        jDodDojazLbl = new javax.swing.JLabel();
        jOpłŻywLbl = new javax.swing.JLabel();
        jTxtDodDoj = new javax.swing.JTextField();
        jTxtOpłŻyw = new javax.swing.JTextField();
        jTxtPremProd = new javax.swing.JTextField();
        jPremiaProdukcyjnaLbl = new javax.swing.JLabel();
        jLNLbl = new javax.swing.JLabel();
        jTxtPensjaLBL = new javax.swing.JLabel();
        jLabel200 = new javax.swing.JLabel();
        jLabel150 = new javax.swing.JLabel();
        jLN150Txt = new javax.swing.JTextField();
        jLN200Txt = new javax.swing.JTextField();
        jPanel2 = new javax.swing.JPanel();
        jEmployeeNameLabel = new javax.swing.JLabel();
        jAdressLabel = new javax.swing.JLabel();
        jWojewodztwo = new javax.swing.JLabel();
        jPostalLabel = new javax.swing.JLabel();
        jTxtImieNazwisko = new javax.swing.JTextField();
        jTxtCountry = new javax.swing.JTextField();
        jTxtAdres = new javax.swing.JTextField();
        jTxtKodPocztowy = new javax.swing.JTextField();
        jPanel3 = new javax.swing.JPanel();
        jEmpoyerNameLabel = new javax.swing.JLabel();
        jRefNoLabel = new javax.swing.JLabel();
        jEmployeeNameLabel2 = new javax.swing.JLabel();
        jTxtNrRef = new javax.swing.JTextField();
        jTxtNip = new javax.swing.JTextField();
        jTxtPracodawca = new javax.swing.JTextField();
        jDisplayDateLBL = new javax.swing.JPanel();
        jPayDateLabel = new javax.swing.JLabel();
        jPayDateChooser = new com.toedter.calendar.JDateChooser();
        jRegEmployeeCB = new javax.swing.JComboBox<>();
        jLabel2 = new javax.swing.JLabel();
        jDataSetBTN = new javax.swing.JButton();
        jSummedPanel = new javax.swing.JPanel();
        jTaxablePayLabel = new javax.swing.JLabel();
        jPensionablePayLabel = new javax.swing.JLabel();
        jTaxPayLBL = new javax.swing.JLabel();
        jPensionPayLBL = new javax.swing.JLabel();
        jPanel7 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel9 = new javax.swing.JPanel();
        jTaxCodeLabel = new javax.swing.JLabel();
        jNIPaymentLabel = new javax.swing.JLabel();
        jNICodeLabel = new javax.swing.JLabel();
        jComboTU = new javax.swing.JComboBox<>();
        jTxtNrUbezpiecz = new javax.swing.JTextField();
        jComboKP = new javax.swing.JComboBox<>();
        jPanel8 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTxtAreaRec = new javax.swing.JTextArea();
        jPanel10 = new javax.swing.JPanel();
        jAddWagesBTN = new javax.swing.JButton();
        jResetBTN = new javax.swing.JButton();
        jPayReferenceBTN = new javax.swing.JButton();
        jNewPayjmentBTN = new javax.swing.JButton();
        jExitBTN = new javax.swing.JButton();
        jPanel6 = new javax.swing.JPanel();
        jSkladEmerytalna = new javax.swing.JLabel();
        jSkładRent = new javax.swing.JLabel();
        jSkładEmerytLBL = new javax.swing.JLabel();
        jSkladRentLBL = new javax.swing.JLabel();
        jSkladChorobowaLBL = new javax.swing.JLabel();
        jSkładChorobowa = new javax.swing.JLabel();
        jSkladZdrowLBL = new javax.swing.JLabel();
        jSkładZdrowotna = new javax.swing.JLabel();
        jPPitLBL = new javax.swing.JLabel();
        jPPit = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jSummarizedEarningsLabel = new javax.swing.JLabel();
        jTxtTelephone = new javax.swing.JTextField();
        jSummarizedTaxesLabel = new javax.swing.JLabel();
        jTxtEmail = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        jPanel1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jEmployeeNameLabel3.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jEmployeeNameLabel3.setText("Employee Name:");

        jPensjaLbl.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jPensjaLbl.setText("Pensja:");

        jDodDojazLbl.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jDodDojazLbl.setText("Dodatek Dojazdowy:");

        jOpłŻywLbl.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jOpłŻywLbl.setText("Opłata Żywieniowa:");

        jTxtDodDoj.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N

        jTxtOpłŻyw.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N

        jTxtPremProd.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N

        jPremiaProdukcyjnaLbl.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jPremiaProdukcyjnaLbl.setText("Premia Produkcyjna:");

        jLNLbl.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLNLbl.setText("Liczba Nadgodzin:");

        jTxtPensjaLBL.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jTxtPensjaLBL.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLabel200.setFont(new java.awt.Font("Tahoma", 0, 13)); // NOI18N
        jLabel200.setText("200% :");

        jLabel150.setFont(new java.awt.Font("Tahoma", 0, 13)); // NOI18N
        jLabel150.setText("150% :");

        jLN150Txt.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLN150Txt.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLN200Txt.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLN200Txt.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jDodDojazLbl, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jOpłŻywLbl, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPremiaProdukcyjnaLbl, javax.swing.GroupLayout.DEFAULT_SIZE, 139, Short.MAX_VALUE)
                    .addComponent(jLNLbl, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPensjaLbl, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jTxtOpłŻyw)
                    .addComponent(jTxtDodDoj)
                    .addComponent(jTxtPensjaLBL, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jTxtPremProd)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel150, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLN150Txt, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel200)
                        .addGap(6, 6, 6)
                        .addComponent(jLN200Txt, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 13, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPensjaLbl, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jTxtPensjaLBL, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jDodDojazLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTxtDodDoj, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jOpłŻywLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTxtOpłŻyw, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(12, 12, 12)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPremiaProdukcyjnaLbl, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jTxtPremProd, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLNLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel150, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLN150Txt, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel200, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLN200Txt, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(21, 21, 21))
        );

        jPanel2.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jEmployeeNameLabel.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jEmployeeNameLabel.setText("Imię i Nazwisko:");

        jAdressLabel.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jAdressLabel.setText("Adres:");

        jWojewodztwo.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jWojewodztwo.setText("Województwo:");

        jPostalLabel.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jPostalLabel.setText("Kod Pocztowy:");

        jTxtImieNazwisko.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N

        jTxtCountry.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N

        jTxtAdres.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N

        jTxtKodPocztowy.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jEmployeeNameLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jAdressLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jWojewodztwo, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPostalLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(14, 14, 14)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jTxtAdres, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jTxtCountry, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jTxtKodPocztowy)
                    .addComponent(jTxtImieNazwisko))
                .addGap(10, 10, 10))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(13, 13, 13)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTxtImieNazwisko, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jEmployeeNameLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jAdressLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTxtAdres, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(10, 10, 10)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jWojewodztwo, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTxtCountry, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(10, 10, 10)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jPostalLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTxtKodPocztowy, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(10, 10, 10))
        );

        jPanel3.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jEmpoyerNameLabel.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jEmpoyerNameLabel.setText("NIP:");

        jRefNoLabel.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jRefNoLabel.setText("Numer Ref:");

        jEmployeeNameLabel2.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jEmployeeNameLabel2.setText("Nazwa Pacodwacy:");

        jTxtNrRef.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N

        jTxtNip.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N

        jTxtPracodawca.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jTxtPracodawca.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTxtPracodawcaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jRefNoLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jEmpoyerNameLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jEmployeeNameLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, 120, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jTxtNip, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jTxtPracodawca, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jTxtNrRef, javax.swing.GroupLayout.Alignment.TRAILING))
                .addGap(10, 10, 10))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jRefNoLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTxtNrRef, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(9, 9, 9)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jEmpoyerNameLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTxtNip, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(9, 9, 9)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jEmployeeNameLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTxtPracodawca, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jDisplayDateLBL.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jPayDateLabel.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jPayDateLabel.setText("Data Przelewu:");

        jPayDateChooser.setDateFormatString("yyyy MM dd");

        jRegEmployeeCB.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jRegEmployeeCB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRegEmployeeCBActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel2.setText("Lista Pracowników:");

        jDataSetBTN.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N
        jDataSetBTN.setText("Ustaw");
        jDataSetBTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jDataSetBTNActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jDisplayDateLBLLayout = new javax.swing.GroupLayout(jDisplayDateLBL);
        jDisplayDateLBL.setLayout(jDisplayDateLBLLayout);
        jDisplayDateLBLLayout.setHorizontalGroup(
            jDisplayDateLBLLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jDisplayDateLBLLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jDisplayDateLBLLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPayDateLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(jDisplayDateLBLLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jDisplayDateLBLLayout.createSequentialGroup()
                        .addComponent(jRegEmployeeCB, javax.swing.GroupLayout.PREFERRED_SIZE, 169, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jDataSetBTN, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jPayDateChooser, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jDisplayDateLBLLayout.setVerticalGroup(
            jDisplayDateLBLLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jDisplayDateLBLLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jDisplayDateLBLLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jDisplayDateLBLLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jRegEmployeeCB, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel2))
                    .addComponent(jDataSetBTN, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jDisplayDateLBLLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPayDateChooser, javax.swing.GroupLayout.DEFAULT_SIZE, 28, Short.MAX_VALUE)
                    .addComponent(jPayDateLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        jSummedPanel.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jTaxablePayLabel.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jTaxablePayLabel.setText("Łączny Podatek:");

        jPensionablePayLabel.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jPensionablePayLabel.setText("Pensja Łącznie:");

        jTaxPayLBL.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jTaxPayLBL.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jPensionPayLBL.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jPensionPayLBL.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        javax.swing.GroupLayout jSummedPanelLayout = new javax.swing.GroupLayout(jSummedPanel);
        jSummedPanel.setLayout(jSummedPanelLayout);
        jSummedPanelLayout.setHorizontalGroup(
            jSummedPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jSummedPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jSummedPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPensionablePayLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jTaxablePayLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(jSummedPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jTaxPayLBL, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPensionPayLBL, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jSummedPanelLayout.setVerticalGroup(
            jSummedPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jSummedPanelLayout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(jSummedPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jTaxablePayLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 45, Short.MAX_VALUE)
                    .addComponent(jTaxPayLBL, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(jSummedPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPensionablePayLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 30, Short.MAX_VALUE)
                    .addComponent(jPensionPayLBL, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(21, 21, 21))
        );

        jPanel7.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setText("Komentarz:");

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel7Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(76, 76, 76))
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 35, Short.MAX_VALUE)
                .addContainerGap())
        );

        jPanel9.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jTaxCodeLabel.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jTaxCodeLabel.setText("Typ Umowy:");

        jNIPaymentLabel.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jNIPaymentLabel.setText("Numer Ubezpieczenia:");

        jNICodeLabel.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jNICodeLabel.setText("Kod Pensji:");

        jComboTU.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jComboTU.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1", "2", "3", "4", "5", "6", "7" }));

        jTxtNrUbezpiecz.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N

        jComboKP.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jComboKP.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "A0000", "A3000", "B4000", "C5000", "D6000", "E7000", "F8000", "G9000" }));

        javax.swing.GroupLayout jPanel9Layout = new javax.swing.GroupLayout(jPanel9);
        jPanel9.setLayout(jPanel9Layout);
        jPanel9Layout.setHorizontalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel9Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel9Layout.createSequentialGroup()
                        .addComponent(jTaxCodeLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jComboTU, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel9Layout.createSequentialGroup()
                        .addComponent(jNICodeLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jComboKP, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel9Layout.createSequentialGroup()
                        .addComponent(jNIPaymentLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 163, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTxtNrUbezpiecz, javax.swing.GroupLayout.PREFERRED_SIZE, 228, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        jPanel9Layout.setVerticalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel9Layout.createSequentialGroup()
                .addContainerGap(14, Short.MAX_VALUE)
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTaxCodeLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jComboTU, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(10, 10, 10)
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jNIPaymentLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTxtNrUbezpiecz, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(8, 8, 8)
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jNICodeLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jComboKP, javax.swing.GroupLayout.DEFAULT_SIZE, 50, Short.MAX_VALUE))
                .addContainerGap())
        );

        jPanel8.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jTxtAreaRec.setColumns(20);
        jTxtAreaRec.setFont(new java.awt.Font("Monospaced", 0, 14)); // NOI18N
        jTxtAreaRec.setRows(5);
        jScrollPane1.setViewportView(jTxtAreaRec);

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1)
                .addContainerGap())
        );
        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 175, Short.MAX_VALUE)
                .addContainerGap())
        );

        jPanel10.setBorder(javax.swing.BorderFactory.createEtchedBorder(java.awt.Color.white, null));

        jAddWagesBTN.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jAddWagesBTN.setText("Zsumuj Płatność");
        jAddWagesBTN.setToolTipText("");
        jAddWagesBTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jAddWagesBTNActionPerformed(evt);
            }
        });

        jResetBTN.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jResetBTN.setText("Reset");
        jResetBTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jResetBTNActionPerformed(evt);
            }
        });

        jPayReferenceBTN.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jPayReferenceBTN.setText("Wypłać");
        jPayReferenceBTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jPayReferenceBTNActionPerformed(evt);
            }
        });

        jNewPayjmentBTN.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jNewPayjmentBTN.setText("Dodaj Pracownika");
        jNewPayjmentBTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jNewPayjmentBTNActionPerformed(evt);
            }
        });

        jExitBTN.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jExitBTN.setText("Wyjście");
        jExitBTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jExitBTNActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel10Layout = new javax.swing.GroupLayout(jPanel10);
        jPanel10.setLayout(jPanel10Layout);
        jPanel10Layout.setHorizontalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel10Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jAddWagesBTN, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jResetBTN, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPayReferenceBTN, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jNewPayjmentBTN, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jExitBTN, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel10Layout.setVerticalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel10Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jAddWagesBTN, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(12, 12, 12)
                .addComponent(jResetBTN, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(12, 12, 12)
                .addComponent(jPayReferenceBTN, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(12, 12, 12)
                .addComponent(jNewPayjmentBTN, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(12, 12, 12)
                .addComponent(jExitBTN, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jPanel6.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jSkladEmerytalna.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jSkladEmerytalna.setText("Składka Emerytalna:");

        jSkładRent.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jSkładRent.setText("Składka Rentowna:");

        jSkładEmerytLBL.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jSkładEmerytLBL.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jSkladRentLBL.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jSkladRentLBL.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jSkladChorobowaLBL.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jSkladChorobowaLBL.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jSkładChorobowa.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jSkładChorobowa.setText("Składka Chorobowa:");

        jSkladZdrowLBL.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jSkladZdrowLBL.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jSkładZdrowotna.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jSkładZdrowotna.setText("Składka Zdrowotna:");

        jPPitLBL.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jPPitLBL.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jPPit.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jPPit.setText("Podatek PIT:");

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPPit, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jSkładZdrowotna, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jSkładChorobowa, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jSkładRent, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jSkladEmerytalna, javax.swing.GroupLayout.DEFAULT_SIZE, 131, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jSkładEmerytLBL, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jSkladRentLBL, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jSkladChorobowaLBL, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jSkladZdrowLBL, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPPitLBL, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jSkładEmerytLBL, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jSkladEmerytalna, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jSkładRent, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jSkladRentLBL, javax.swing.GroupLayout.DEFAULT_SIZE, 34, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jSkładChorobowa, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jSkladChorobowaLBL, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jSkładZdrowotna, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jSkladZdrowLBL, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPPit, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPPitLBL, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        jPanel4.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jSummarizedEarningsLabel.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jSummarizedEarningsLabel.setText("Numer Telefonu:");

        jTxtTelephone.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N

        jSummarizedTaxesLabel.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jSummarizedTaxesLabel.setText("Adres Email:");

        jTxtEmail.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jSummarizedTaxesLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jSummarizedEarningsLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 124, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jTxtEmail)
                    .addComponent(jTxtTelephone))
                .addContainerGap())
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jSummarizedEarningsLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTxtTelephone, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jSummarizedTaxesLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTxtEmail, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel9, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jSummedPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jDisplayDateLBL, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel10, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jDisplayDateLBL, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jPanel8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jPanel9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(6, 6, 6)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jSummedPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jPanel10, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    
    public void resetScript(){
        jTxtImieNazwisko.setText(null);
       jTxtNip.setText(null);
       jTxtPracodawca.setText(null);
       jTxtAdres.setText(null);
       jTxtCountry.setText(null);
       jTxtKodPocztowy.setText(null);
       jTxtNrRef.setText(null);
       jTxtPensjaLBL.setText(null);
       jTxtDodDoj.setText(null);
       jTxtOpłŻyw.setText(null);
       jTxtNrUbezpiecz.setText(null);
       jTxtAreaRec.setText(null);
       jSkładEmerytLBL.setText(null);
       jSkladRentLBL.setText(null);
       jTaxPayLBL.setText(null);
       jPensionPayLBL.setText(null);
       jTxtTelephone.setText(null);
       jTxtEmail.setText(null);
       jTxtPremProd.setText(null);
       jLN150Txt.setText(null);
       jLN200Txt.setText(null);
       jComboTU.setSelectedItem("1");
       jComboKP.setSelectedItem("A0000");
       jPayDateChooser.setDate(null);
       jSkladChorobowaLBL.setText(null);
       jSkladZdrowLBL.setText(null);
       jPPitLBL.setText(null);
    }
    
    private void wages(){
       
       
       if(jComboKP.getSelectedItem().equals("A0000")){
           jTxtPensjaLBL.setText("2250");
       }
       else if(jComboKP.getSelectedItem().equals("A3000")){
           jTxtPensjaLBL.setText("3000");
       }
       else if(jComboKP.getSelectedItem().equals("B4000")){
           jTxtPensjaLBL.setText("4000");
       }
       else if(jComboKP.getSelectedItem().equals("C5000")){
           jTxtPensjaLBL.setText("5000");
       }
       else if(jComboKP.getSelectedItem().equals("D6000")){
           jTxtPensjaLBL.setText("6000");
       }
       else if(jComboKP.getSelectedItem().equals("E7000")){
           jTxtPensjaLBL.setText("7000");
       }
       else if(jComboKP.getSelectedItem().equals("F8000")){
           jTxtPensjaLBL.setText("8000");
       }
       else if(jComboKP.getSelectedItem().equals("G9000")){
           jTxtPensjaLBL.setText("9000");
       }
       
       
    }
    
    private void jTxtPracodawcaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTxtPracodawcaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTxtPracodawcaActionPerformed

    private void jExitBTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jExitBTNActionPerformed
        System.exit(0);
    }//GEN-LAST:event_jExitBTNActionPerformed

    private void jResetBTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jResetBTNActionPerformed
      this.resetScript();
               
    }//GEN-LAST:event_jResetBTNActionPerformed

    private void jAddWagesBTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jAddWagesBTNActionPerformed
        
        
        double SkladkaEmerytalna, SkladkaRentowna, SkladkaChorobowa, SkladkaZdrowotna, PodatekPIT, SummarizedNad, Nad200, 
                SumNad200, Nad150, SumNad150, CaZar;
        
   
        
          this.wages();
        
    
          
          PensjaPodstawowa = Double.parseDouble(jTxtPensjaLBL.getText());
          
          PremiaProdukcyjna = Double.parseDouble(jTxtPremProd.getText());
          
          DodDojazdowy = Double.parseDouble(jTxtDodDoj.getText());
          
          OplataZywieniowa = Double.parseDouble(jTxtOpłŻyw.getText());
        
    
          Nad150 = Double.parseDouble(jLN150Txt.getText());
          
          SumNad150 = ((PensjaPodstawowa % 160) * 1.5) * Nad150;
          
          Nad200 = Double.parseDouble(jLN200Txt.getText());
          
          SumNad200 = ((PensjaPodstawowa % 160) * 2) * Nad200;
          
          SummarizedNad = SumNad150 + SumNad200;
          
          CaZar = PensjaPodstawowa + SummarizedNad;
          
         
          
          SkladkaEmerytalna = CaZar * 0.0976; 
          SkladkaRentowna = CaZar * 0.015;
          SkladkaChorobowa = CaZar * 0.0245;
          SkladkaZdrowotna = CaZar * 0.0777;
          PodatekPIT = CaZar * 0.0723;
          LacznyPodatek = SkladkaEmerytalna + SkladkaRentowna + SkladkaChorobowa + SkladkaZdrowotna + PodatekPIT;
          SummPension = CaZar - LacznyPodatek + DodDojazdowy + PremiaProdukcyjna - OplataZywieniowa;
          
      try{
       
            if(jComboKP.getSelectedItem().equals("A0000")){
               
                
                
               String SkEm = String.format("%.2f", SkladkaEmerytalna);  
               jSkładEmerytLBL.setText(SkEm + "zł");
               
               String SkRen = String.format("%.2f", SkladkaRentowna);  
               jSkladRentLBL.setText(SkRen + "zł");
               
               String SkChor = String.format("%.2f", SkladkaChorobowa);  
               jSkladChorobowaLBL.setText(SkChor + "zł");
               
               String SkZdrow = String.format("%.2f", SkladkaZdrowotna);  
               jSkladZdrowLBL.setText(SkZdrow + "zł");
               
               String PodPIT = String.format("%.2f", PodatekPIT);  
               jPPitLBL.setText(PodPIT + "zł");
               
               String SumPod = String.format("%.2f", LacznyPodatek);  
               jTaxPayLBL.setText(SumPod + "zł");
               
               String SummarizedPension = String.format("%.2f", SummPension);
               jPensionPayLBL.setText(SummarizedPension + "zł");
               
              
               
            }
            
            else if(jComboKP.getSelectedItem().equals("A3000")){
                
               String SkEm = String.format("%.2f", SkladkaEmerytalna);  
               jSkładEmerytLBL.setText(SkEm + "zł");
               
               String SkRen = String.format("%.2f", SkladkaRentowna);  
               jSkladRentLBL.setText(SkRen + "zł");
               
               String SkChor = String.format("%.2f", SkladkaChorobowa);  
               jSkladChorobowaLBL.setText(SkChor + "zł");
               
               String SkZdrow = String.format("%.2f", SkladkaZdrowotna);  
               jSkladZdrowLBL.setText(SkZdrow + "zł");
               
               String PodPIT = String.format("%.2f", PodatekPIT);  
               jPPitLBL.setText(PodPIT + "zł");
               
               String SumPod = String.format("%.2f", LacznyPodatek);  
               jTaxPayLBL.setText(SumPod + "zł");
               
               String SummarizedPension = String.format("%.2f", SummPension);
               jPensionPayLBL.setText(SummarizedPension + "zł");
                
            }
            
            
             else if(jComboKP.getSelectedItem().equals("B4000")){
                
               String SkEm = String.format("%.2f", SkladkaEmerytalna);  
               jSkładEmerytLBL.setText(SkEm + "zł");
               
               String SkRen = String.format("%.2f", SkladkaRentowna);  
               jSkladRentLBL.setText(SkRen + "zł");
               
               String SkChor = String.format("%.2f", SkladkaChorobowa);  
               jSkladChorobowaLBL.setText(SkChor + "zł");
               
               String SkZdrow = String.format("%.2f", SkladkaZdrowotna);  
               jSkladZdrowLBL.setText(SkZdrow + "zł");
               
               String PodPIT = String.format("%.2f", PodatekPIT);  
               jPPitLBL.setText(PodPIT + "zł");
               
               String SumPod = String.format("%.2f", LacznyPodatek);  
               jTaxPayLBL.setText(SumPod + "zł");
               
               String SummarizedPension = String.format("%.2f", SummPension);
               jPensionPayLBL.setText(SummarizedPension + "zł"); 
                
            }
            
             else if(jComboKP.getSelectedItem().equals("C5000")){
                
               String SkEm = String.format("%.2f", SkladkaEmerytalna);  
               jSkładEmerytLBL.setText(SkEm + "zł");
               
               String SkRen = String.format("%.2f", SkladkaRentowna);  
               jSkladRentLBL.setText(SkRen + "zł");
               
               String SkChor = String.format("%.2f", SkladkaChorobowa);  
               jSkladChorobowaLBL.setText(SkChor + "zł");
               
               String SkZdrow = String.format("%.2f", SkladkaZdrowotna);  
               jSkladZdrowLBL.setText(SkZdrow + "zł");
               
               String PodPIT = String.format("%.2f", PodatekPIT);  
               jPPitLBL.setText(PodPIT + "zł");
               
               String SumPod = String.format("%.2f", LacznyPodatek);  
               jTaxPayLBL.setText(SumPod + "zł");
               
               String SummarizedPension = String.format("%.2f", SummPension);
               jPensionPayLBL.setText(SummarizedPension + "zł");
                
            }
            
             else if(jComboKP.getSelectedItem().equals("D6000")){
                
               String SkEm = String.format("%.2f", SkladkaEmerytalna);  
               jSkładEmerytLBL.setText(SkEm + "zł");
               
               String SkRen = String.format("%.2f", SkladkaRentowna);  
               jSkladRentLBL.setText(SkRen + "zł");
               
               String SkChor = String.format("%.2f", SkladkaChorobowa);  
               jSkladChorobowaLBL.setText(SkChor + "zł");
               
               String SkZdrow = String.format("%.2f", SkladkaZdrowotna);  
               jSkladZdrowLBL.setText(SkZdrow + "zł");
               
               String PodPIT = String.format("%.2f", PodatekPIT);  
               jPPitLBL.setText(PodPIT + "zł");
               
               String SumPod = String.format("%.2f", LacznyPodatek);  
               jTaxPayLBL.setText(SumPod + "zł");
               
               String SummarizedPension = String.format("%.2f", SummPension);
               jPensionPayLBL.setText(SummarizedPension + "zł"); 
                
            }
            
             else if(jComboKP.getSelectedItem().equals("E7000")){
                
               String SkEm = String.format("%.2f", SkladkaEmerytalna);  
               jSkładEmerytLBL.setText(SkEm + "zł");
               
               String SkRen = String.format("%.2f", SkladkaRentowna);  
               jSkladRentLBL.setText(SkRen + "zł");
               
               String SkChor = String.format("%.2f", SkladkaChorobowa);  
               jSkladChorobowaLBL.setText(SkChor + "zł");
               
               String SkZdrow = String.format("%.2f", SkladkaZdrowotna);  
               jSkladZdrowLBL.setText(SkZdrow + "zł");
               
               String PodPIT = String.format("%.2f", PodatekPIT);  
               jPPitLBL.setText(PodPIT + "zł");
               
               String SumPod = String.format("%.2f", LacznyPodatek);  
               jTaxPayLBL.setText(SumPod + "zł");
               
               String SummarizedPension = String.format("%.2f", SummPension);
               jPensionPayLBL.setText(SummarizedPension + "zł"); 
                
            }
            
             else if(jComboKP.getSelectedItem().equals("F8000")){
                
               String SkEm = String.format("%.2f", SkladkaEmerytalna);  
               jSkładEmerytLBL.setText(SkEm + "zł");
               
               String SkRen = String.format("%.2f", SkladkaRentowna);  
               jSkladRentLBL.setText(SkRen + "zł");
               
               String SkChor = String.format("%.2f", SkladkaChorobowa);  
               jSkladChorobowaLBL.setText(SkChor + "zł");
               
               String SkZdrow = String.format("%.2f", SkladkaZdrowotna);  
               jSkladZdrowLBL.setText(SkZdrow + "zł");
               
               String PodPIT = String.format("%.2f", PodatekPIT);  
               jPPitLBL.setText(PodPIT + "zł");
               
               String SumPod = String.format("%.2f", LacznyPodatek);  
               jTaxPayLBL.setText(SumPod + "zł");
               
               String SummarizedPension = String.format("%.2f", SummPension);
               jPensionPayLBL.setText(SummarizedPension + "zł"); 
                
            }
            
             else if(jComboKP.getSelectedItem().equals("G9000")){
                
               String SkEm = String.format("%.2f", SkladkaEmerytalna);  
               jSkładEmerytLBL.setText(SkEm + "zł");
               
               String SkRen = String.format("%.2f", SkladkaRentowna);  
               jSkladRentLBL.setText(SkRen + "zł");
               
               String SkChor = String.format("%.2f", SkladkaChorobowa);  
               jSkladChorobowaLBL.setText(SkChor + "zł");
               
               String SkZdrow = String.format("%.2f", SkladkaZdrowotna);  
               jSkladZdrowLBL.setText(SkZdrow + "zł");
               
               String PodPIT = String.format("%.2f", PodatekPIT);  
               jPPitLBL.setText(PodPIT + "zł");
               
               String SumPod = String.format("%.2f", LacznyPodatek);  
               jTaxPayLBL.setText(SumPod + "zł");
               
               String SummarizedPension = String.format("%.2f", SummPension);
               jPensionPayLBL.setText(SummarizedPension + "zł"); 
                
            }
           
            
        }
        catch (NumberFormatException e){
            JOptionPane.showMessageDialog(null, "Enter a Valid Number", "Only Numbers", JOptionPane.INFORMATION_MESSAGE);
            
            jTxtImieNazwisko.setText(null);
            jTxtNip.setText(null);
            jTxtPracodawca.setText(null);
            jTxtAdres.setText(null);
            jTxtCountry.setText(null);
            jTxtKodPocztowy.setText(null);
            jTxtNrRef.setText(null);
            jTxtPensjaLBL.setText(null);
            jTxtDodDoj.setText(null);
            jTxtOpłŻyw.setText(null);
            jTxtNrUbezpiecz.setText(null);
            jTxtAreaRec.setText(null);
            jSkładEmerytLBL.setText(null);
            jSkladRentLBL.setText(null);
            jTaxPayLBL.setText(null);
            jPensionPayLBL.setText(null);
            jTxtTelephone.setText(null);
            jTxtEmail.setText(null);
            jTxtPremProd.setText(null);
            jLN150Txt.setText(null);
            jLN200Txt.setText(null);
            jComboTU.setSelectedItem("1");
            jComboKP.setSelectedItem("A0000");
            jPayDateChooser.setDate(null);
            jSkladChorobowaLBL.setText(null);
            jSkladZdrowLBL.setText(null);
            jPPitLBL.setText(null);
        }
    }//GEN-LAST:event_jAddWagesBTNActionPerformed

    @SuppressWarnings("deprecation")
    private void jNewPayjmentBTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jNewPayjmentBTNActionPerformed
       this.resetScript();
       
       Employee_Registration_Poland erp = new Employee_Registration_Poland();
        this.setVisible(false);
       erp.setVisible(true);
    }//GEN-LAST:event_jNewPayjmentBTNActionPerformed

    private void jRegEmployeeCBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRegEmployeeCBActionPerformed

    }//GEN-LAST:event_jRegEmployeeCBActionPerformed

    private void jDataSetBTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jDataSetBTNActionPerformed
        String tmp = (String) jRegEmployeeCB.getSelectedItem();
            String sql = "select * from emloyee_list_poland where prac_name = ?";
            
            
        try{
           
            con_emp_list = DriverManager.getConnection("jdbc:mysql://localhost:3306/paymentsys", "root", "");
            prepstat = con_emp_list.prepareStatement(sql);
            prepstat.setString(1, tmp);
            resSet = prepstat.executeQuery();
            
            if(resSet.next()){
                
                String empname = resSet.getString("prac_name");
                jTxtImieNazwisko.setText(empname);
                
                String empaddress = resSet.getString("prac_address");
                jTxtAdres.setText(empaddress);
                
                String empcountry = resSet.getString("prac_country");
                jTxtCountry.setText(empcountry);
                
                String emppostal= resSet.getString("prac_postal_code");
                jTxtKodPocztowy.setText(emppostal);
                
                String emprefno = resSet.getString("prac_ref_no");
                jTxtNrRef.setText(emprefno);
                
                String empemployer = resSet.getString("prac_employer");
                jTxtPracodawca.setText(empemployer);
                
                String empphone = resSet.getString("prac_phone_number");
                jTxtTelephone.setText(empphone);
                
                String empemail = resSet.getString("prac_email");
                jTxtEmail.setText(empemail);
                
            }
        }
        
        catch(SQLException e){
            
            JOptionPane.showMessageDialog(null, e);
            
        }       
    }//GEN-LAST:event_jDataSetBTNActionPerformed

    private void jPayReferenceBTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jPayReferenceBTNActionPerformed
        
        DateFormat df = new SimpleDateFormat("yyyy-MM-dd");
        
        String name = jTxtImieNazwisko.getText();
        String address = jTxtAdres.getText();
        String country = jTxtCountry.getText();
        String postal_code = jTxtKodPocztowy.getText();
        String ref_no = jTxtNrRef.getText();
        String employer_name = jTxtPracodawca.getText();
        String phone_number = jTxtTelephone.getText();
        String nip = jTxtNip.getText();
        String email = jTxtEmail.getText();
        String pension = jPensionPayLBL.getText();
        String date = df.format(jPayDateChooser.getDate());
        
        
        
        try{
            
            Class.forName("com.mysql.cj.jdbc.Driver");
            con_user_data = DriverManager.getConnection("jdbc:mysql://localhost:3306/paymentsys", "root", "");
            pstmt = con_user_data.prepareStatement("insert into user_data_pl values (?, ?, ? , ? , ?, ?, ?, ?, ?, ?, ?)");
            
            pstmt.setString(1, name);
            pstmt.setString(2, address);
            pstmt.setString(3, country);
            pstmt.setString(4, postal_code);
            pstmt.setString(5, ref_no);
            pstmt.setString(6, employer_name);
            pstmt.setString(7, phone_number);
            pstmt.setString(8, nip);
            pstmt.setString(9, email);
            pstmt.setString(10, pension);
            pstmt.setString(11, date);
            
            int i = pstmt.executeUpdate();
            
            if(i>0){
                JOptionPane.showMessageDialog(null, "Data is Saved");
            }
            else{
            JOptionPane.showMessageDialog(null, "Data is Not Saved");
            }
            
            this.resetScript();
            
        }
        catch(HeadlessException | ClassNotFoundException | SQLException e){
            JOptionPane.showMessageDialog(null, e);
        }
    }//GEN-LAST:event_jPayReferenceBTNActionPerformed

    
    private void fillCombo(){
        
        try{
            
            String sql = "select * from emloyee_list_poland";
            con_emp_list = DriverManager.getConnection("jdbc:mysql://localhost:3306/paymentsys", "root", "");
            prepstat = con_emp_list.prepareStatement(sql);
            resSet = prepstat.executeQuery();
            while(resSet.next()){
               
                String name = resSet.getString("prac_name");
                jRegEmployeeCB.addItem(name);
              
             
            }
        }
        
        catch(SQLException e){
            
            JOptionPane.showMessageDialog(null, e);
            
        }
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PaymentsystemPoland.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PaymentsystemPoland.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PaymentsystemPoland.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PaymentsystemPoland.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PaymentsystemPoland().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jAddWagesBTN;
    private javax.swing.JLabel jAdressLabel;
    private javax.swing.JComboBox<String> jComboKP;
    private javax.swing.JComboBox<String> jComboTU;
    private javax.swing.JButton jDataSetBTN;
    private javax.swing.JPanel jDisplayDateLBL;
    private javax.swing.JLabel jDodDojazLbl;
    private javax.swing.JLabel jEmployeeNameLabel;
    private javax.swing.JLabel jEmployeeNameLabel2;
    private javax.swing.JLabel jEmployeeNameLabel3;
    private javax.swing.JLabel jEmpoyerNameLabel;
    private javax.swing.JButton jExitBTN;
    private javax.swing.JTextField jLN150Txt;
    private javax.swing.JTextField jLN200Txt;
    private javax.swing.JLabel jLNLbl;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel150;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel200;
    private javax.swing.JLabel jNICodeLabel;
    private javax.swing.JLabel jNIPaymentLabel;
    private javax.swing.JButton jNewPayjmentBTN;
    private javax.swing.JLabel jOpłŻywLbl;
    private javax.swing.JLabel jPPit;
    private javax.swing.JLabel jPPitLBL;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private com.toedter.calendar.JDateChooser jPayDateChooser;
    private javax.swing.JLabel jPayDateLabel;
    private javax.swing.JButton jPayReferenceBTN;
    private javax.swing.JLabel jPensionPayLBL;
    private javax.swing.JLabel jPensionablePayLabel;
    private javax.swing.JLabel jPensjaLbl;
    private javax.swing.JLabel jPostalLabel;
    private javax.swing.JLabel jPremiaProdukcyjnaLbl;
    private javax.swing.JLabel jRefNoLabel;
    private javax.swing.JComboBox<String> jRegEmployeeCB;
    private javax.swing.JButton jResetBTN;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel jSkladChorobowaLBL;
    private javax.swing.JLabel jSkladEmerytalna;
    private javax.swing.JLabel jSkladRentLBL;
    private javax.swing.JLabel jSkladZdrowLBL;
    private javax.swing.JLabel jSkładChorobowa;
    private javax.swing.JLabel jSkładEmerytLBL;
    private javax.swing.JLabel jSkładRent;
    private javax.swing.JLabel jSkładZdrowotna;
    private javax.swing.JLabel jSummarizedEarningsLabel;
    private javax.swing.JLabel jSummarizedTaxesLabel;
    private javax.swing.JPanel jSummedPanel;
    private javax.swing.JLabel jTaxCodeLabel;
    private javax.swing.JLabel jTaxPayLBL;
    private javax.swing.JLabel jTaxablePayLabel;
    private javax.swing.JTextField jTxtAdres;
    private javax.swing.JTextArea jTxtAreaRec;
    private javax.swing.JTextField jTxtCountry;
    private javax.swing.JTextField jTxtDodDoj;
    private javax.swing.JTextField jTxtEmail;
    private javax.swing.JTextField jTxtImieNazwisko;
    private javax.swing.JTextField jTxtKodPocztowy;
    private javax.swing.JTextField jTxtNip;
    private javax.swing.JTextField jTxtNrRef;
    private javax.swing.JTextField jTxtNrUbezpiecz;
    private javax.swing.JTextField jTxtOpłŻyw;
    private javax.swing.JLabel jTxtPensjaLBL;
    private javax.swing.JTextField jTxtPracodawca;
    private javax.swing.JTextField jTxtPremProd;
    private javax.swing.JTextField jTxtTelephone;
    private javax.swing.JLabel jWojewodztwo;
    // End of variables declaration//GEN-END:variables
}
