package paymentsys;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

import java.awt.Dimension;
import java.awt.HeadlessException;
import java.awt.Toolkit;
import javax.swing.JOptionPane;
import java.sql.*;
import java.text.DateFormat;
import java.text.SimpleDateFormat;
/**
 *
 * @author Wiktor
 */
public class Paymentsystem extends javax.swing.JFrame {
    double InnerCity;
    double BasicWage;
    double OverTime;
    double Gross;
   
    Connection con_emp_list = null;
    PreparedStatement prepstat = null;
    ResultSet resSet = null; 
    
    Connection con_user_data = null;
    PreparedStatement pstmt = null;
    
    /**
     * Creates new form Paymentsystem
     */
    public Paymentsystem() {
        initComponents();
        
        Toolkit toolkit = getToolkit();
        Dimension size = toolkit.getScreenSize();
        setLocation(size.width/2 - getWidth()/2, size.height/2 - getHeight()/2);
        
        this.fillCombo();
//        this.updateCombo();
        
    }

    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jEmployeeNameLabel3 = new javax.swing.JLabel();
        jInnerCityLabel = new javax.swing.JLabel();
        jBasicSalaryLabel = new javax.swing.JLabel();
        jOverTimeLabel = new javax.swing.JLabel();
        jTxtICW = new javax.swing.JTextField();
        jTxtBS = new javax.swing.JTextField();
        jTxtOT = new javax.swing.JTextField();
        jPanel2 = new javax.swing.JPanel();
        jEmployeeNameLabel = new javax.swing.JLabel();
        jAdressLabel = new javax.swing.JLabel();
        jCountryLabel = new javax.swing.JLabel();
        jPostalLabel = new javax.swing.JLabel();
        jTxtEmployeeName = new javax.swing.JTextField();
        jTxtCountry = new javax.swing.JTextField();
        jTxtAddress = new javax.swing.JTextField();
        jTxtPostal = new javax.swing.JTextField();
        jRegEmployeeLBL = new javax.swing.JLabel();
        jRegEmployeeCB = new javax.swing.JComboBox<>();
        jDataSetBTN = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jEmpoyerNameLabel = new javax.swing.JLabel();
        jRefNoLabel = new javax.swing.JLabel();
        jPhoneNumberLabel = new javax.swing.JLabel();
        jTxtRefNo = new javax.swing.JTextField();
        jTxtEmployer = new javax.swing.JTextField();
        jTxtPhoneNumber = new javax.swing.JTextField();
        jDisplayDateLBL = new javax.swing.JPanel();
        jPayDateLabel = new javax.swing.JLabel();
        jPayDateChooser = new com.toedter.calendar.JDateChooser();
        jPanel5 = new javax.swing.JPanel();
        jTaxablePayLabel = new javax.swing.JLabel();
        jPensionablePayLabel = new javax.swing.JLabel();
        jTaxPayLBL = new javax.swing.JLabel();
        jPensionPayLBL = new javax.swing.JLabel();
        jPanel7 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel9 = new javax.swing.JPanel();
        jTaxPeriodLabel = new javax.swing.JLabel();
        jTaxCodeLabel = new javax.swing.JLabel();
        jNIPaymentLabel = new javax.swing.JLabel();
        jNICodeLabel = new javax.swing.JLabel();
        jComboTP = new javax.swing.JComboBox<>();
        jComboTC = new javax.swing.JComboBox<>();
        jTxtNIPayment = new javax.swing.JTextField();
        jComboNIC = new javax.swing.JComboBox<>();
        jPanel8 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTxtAreaRec = new javax.swing.JTextArea();
        jPanel10 = new javax.swing.JPanel();
        jAddWagesBTN = new javax.swing.JButton();
        jResetBTN = new javax.swing.JButton();
        jPayReferenceBTN = new javax.swing.JButton();
        jNewEmployeeBTN = new javax.swing.JButton();
        jExitBTN = new javax.swing.JButton();
        jPanel6 = new javax.swing.JPanel();
        jTaxLabel = new javax.swing.JLabel();
        jPensionLabel = new javax.swing.JLabel();
        jStudentLoanLabel = new javax.swing.JLabel();
        jNIPayLabel = new javax.swing.JLabel();
        jTaxLBL = new javax.swing.JLabel();
        jPensionLBL = new javax.swing.JLabel();
        jStudenLoanLBL = new javax.swing.JLabel();
        jNIPaymentLBL = new javax.swing.JLabel();
        jPanel11 = new javax.swing.JPanel();
        jNetPayLabel = new javax.swing.JLabel();
        jNetPayLBL = new javax.swing.JLabel();
        jPanel12 = new javax.swing.JPanel();
        jDeductionsLabel = new javax.swing.JLabel();
        jDeductionsLBL = new javax.swing.JLabel();
        jPanel13 = new javax.swing.JPanel();
        jGrossPayLabel = new javax.swing.JLabel();
        jGrsPayLBL = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        jPanel1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jEmployeeNameLabel3.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jEmployeeNameLabel3.setText("Employee Name:");

        jInnerCityLabel.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jInnerCityLabel.setText("Inner City Weighting:");

        jBasicSalaryLabel.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jBasicSalaryLabel.setText("Basic Salary:");

        jOverTimeLabel.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jOverTimeLabel.setText("Over Time:");

        jTxtICW.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N

        jTxtBS.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N

        jTxtOT.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jInnerCityLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTxtICW))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jOverTimeLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(25, 25, 25)
                        .addComponent(jTxtOT))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jBasicSalaryLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(25, 25, 25)
                        .addComponent(jTxtBS)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jInnerCityLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTxtICW, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jBasicSalaryLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTxtBS, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jOverTimeLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTxtOT, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        jPanel2.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jEmployeeNameLabel.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jEmployeeNameLabel.setText("Employee Name:");

        jAdressLabel.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jAdressLabel.setText("Address:");

        jCountryLabel.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jCountryLabel.setText("Country:");

        jPostalLabel.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jPostalLabel.setText("Postal Code:");

        jTxtEmployeeName.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N

        jTxtCountry.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N

        jTxtAddress.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N

        jTxtPostal.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N

        jRegEmployeeLBL.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jRegEmployeeLBL.setText("Employees List:");

        jRegEmployeeCB.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jRegEmployeeCB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRegEmployeeCBActionPerformed(evt);
            }
        });

        jDataSetBTN.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jDataSetBTN.setText("Set");
        jDataSetBTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jDataSetBTNActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jAdressLabel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jCountryLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jPostalLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jEmployeeNameLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jRegEmployeeLBL))
                .addGap(12, 12, 12)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jTxtPostal)
                        .addGap(10, 10, 10))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel2Layout.createSequentialGroup()
                                .addComponent(jRegEmployeeCB, javax.swing.GroupLayout.PREFERRED_SIZE, 176, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jDataSetBTN, javax.swing.GroupLayout.DEFAULT_SIZE, 67, Short.MAX_VALUE))
                            .addComponent(jTxtEmployeeName, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTxtAddress, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTxtCountry))
                        .addContainerGap())))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jRegEmployeeCB)
                        .addComponent(jRegEmployeeLBL, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(jDataSetBTN, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jEmployeeNameLabel)
                    .addComponent(jTxtEmployeeName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTxtAddress, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jAdressLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTxtCountry, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jCountryLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTxtPostal, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPostalLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        jPanel3.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jEmpoyerNameLabel.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jEmpoyerNameLabel.setText("Employer Name:");

        jRefNoLabel.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jRefNoLabel.setText("Reference No:");

        jPhoneNumberLabel.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jPhoneNumberLabel.setText("Phone Number");

        jTxtRefNo.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N

        jTxtEmployer.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N

        jTxtPhoneNumber.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jTxtPhoneNumber.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTxtPhoneNumberActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jRefNoLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPhoneNumberLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jEmpoyerNameLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(14, 14, 14)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jTxtEmployer, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jTxtRefNo)
                    .addComponent(jTxtPhoneNumber, javax.swing.GroupLayout.Alignment.TRAILING))
                .addGap(10, 10, 10))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jRefNoLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTxtRefNo, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jEmpoyerNameLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTxtEmployer, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jPhoneNumberLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTxtPhoneNumber, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(25, Short.MAX_VALUE))
        );

        jDisplayDateLBL.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jPayDateLabel.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jPayDateLabel.setText("Pay Date:");

        jPayDateChooser.setDateFormatString("yyyy MM dd");

        javax.swing.GroupLayout jDisplayDateLBLLayout = new javax.swing.GroupLayout(jDisplayDateLBL);
        jDisplayDateLBL.setLayout(jDisplayDateLBLLayout);
        jDisplayDateLBLLayout.setHorizontalGroup(
            jDisplayDateLBLLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jDisplayDateLBLLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPayDateLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPayDateChooser, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jDisplayDateLBLLayout.setVerticalGroup(
            jDisplayDateLBLLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jDisplayDateLBLLayout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addGroup(jDisplayDateLBLLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPayDateChooser, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPayDateLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 25, Short.MAX_VALUE))
                .addGap(15, 15, 15))
        );

        jPanel5.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jTaxablePayLabel.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jTaxablePayLabel.setText("Taxable Pay:");

        jPensionablePayLabel.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jPensionablePayLabel.setText("Pensionable Pay:");

        jTaxPayLBL.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jTaxPayLBL.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jPensionPayLBL.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jPensionPayLBL.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPensionablePayLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 180, Short.MAX_VALUE)
                    .addComponent(jTaxablePayLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jTaxPayLBL, javax.swing.GroupLayout.DEFAULT_SIZE, 184, Short.MAX_VALUE)
                    .addComponent(jPensionPayLBL, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jTaxablePayLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGap(3, 3, 3)
                        .addComponent(jTaxPayLBL, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPensionablePayLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPensionPayLBL, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(28, 28, 28))
        );

        jPanel7.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setText("Recommendations:");

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addGap(61, 61, 61)
                .addComponent(jLabel1)
                .addGap(50, 50, 50))
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        jPanel9.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jTaxPeriodLabel.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jTaxPeriodLabel.setText("Tax Period:");

        jTaxCodeLabel.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jTaxCodeLabel.setText("Tax Code:");

        jNIPaymentLabel.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jNIPaymentLabel.setText("NI Payment:");

        jNICodeLabel.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jNICodeLabel.setText("NI Code:");

        jComboTP.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jComboTP.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1", "2", "3", "4", "5", "6", "7", "8", "9", "10", "11", "12" }));

        jComboTC.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jComboTC.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "A", "B", "C", "D", "E", "F", "G" }));

        jComboNIC.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jComboNIC.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "A0000", "A3000", "B4000", "C5000", "D6000", "E7000", "F8000", "G9000" }));

        javax.swing.GroupLayout jPanel9Layout = new javax.swing.GroupLayout(jPanel9);
        jPanel9.setLayout(jPanel9Layout);
        jPanel9Layout.setHorizontalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel9Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel9Layout.createSequentialGroup()
                        .addComponent(jTaxPeriodLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jComboTP, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel9Layout.createSequentialGroup()
                        .addComponent(jTaxCodeLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jComboTC, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel9Layout.createSequentialGroup()
                        .addComponent(jNICodeLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jComboNIC, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel9Layout.createSequentialGroup()
                        .addComponent(jNIPaymentLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTxtNIPayment)))
                .addContainerGap())
        );
        jPanel9Layout.setVerticalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel9Layout.createSequentialGroup()
                .addGap(13, 13, 13)
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jComboTP, javax.swing.GroupLayout.DEFAULT_SIZE, 50, Short.MAX_VALUE)
                    .addComponent(jTaxPeriodLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(10, 10, 10)
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTaxCodeLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jComboTC, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(10, 10, 10)
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jNIPaymentLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTxtNIPayment, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(10, 10, 10)
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jNICodeLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jComboNIC, javax.swing.GroupLayout.DEFAULT_SIZE, 50, Short.MAX_VALUE))
                .addContainerGap())
        );

        jPanel8.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jTxtAreaRec.setColumns(20);
        jTxtAreaRec.setRows(5);
        jScrollPane1.setViewportView(jTxtAreaRec);

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1)
                .addContainerGap())
        );
        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1)
                .addContainerGap())
        );

        jPanel10.setBorder(javax.swing.BorderFactory.createEtchedBorder(java.awt.Color.white, null));

        jAddWagesBTN.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jAddWagesBTN.setText("Add Wages");
        jAddWagesBTN.setToolTipText("");
        jAddWagesBTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jAddWagesBTNActionPerformed(evt);
            }
        });

        jResetBTN.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jResetBTN.setText("Reset");
        jResetBTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jResetBTNActionPerformed(evt);
            }
        });

        jPayReferenceBTN.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jPayReferenceBTN.setText("Pay Reference");
        jPayReferenceBTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jPayReferenceBTNActionPerformed(evt);
            }
        });
        jPayReferenceBTN.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jPayReferenceBTNKeyReleased(evt);
            }
        });

        jNewEmployeeBTN.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jNewEmployeeBTN.setText("Add Employee");
        jNewEmployeeBTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jNewEmployeeBTNActionPerformed(evt);
            }
        });

        jExitBTN.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jExitBTN.setText("Exit");
        jExitBTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jExitBTNActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel10Layout = new javax.swing.GroupLayout(jPanel10);
        jPanel10.setLayout(jPanel10Layout);
        jPanel10Layout.setHorizontalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel10Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jAddWagesBTN, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jResetBTN, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPayReferenceBTN, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jNewEmployeeBTN, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jExitBTN, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel10Layout.setVerticalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel10Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jAddWagesBTN, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(12, 12, 12)
                .addComponent(jResetBTN, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(12, 12, 12)
                .addComponent(jPayReferenceBTN, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(12, 12, 12)
                .addComponent(jNewEmployeeBTN, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(12, 12, 12)
                .addComponent(jExitBTN, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jPanel6.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jTaxLabel.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jTaxLabel.setText("Tax:");

        jPensionLabel.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jPensionLabel.setText("Pension:");

        jStudentLoanLabel.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jStudentLoanLabel.setText("Student Loan:");

        jNIPayLabel.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jNIPayLabel.setText("NI Payment:");

        jTaxLBL.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jTaxLBL.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jPensionLBL.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jPensionLBL.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jStudenLoanLBL.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jStudenLoanLBL.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jNIPaymentLBL.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jNIPaymentLBL.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jNIPayLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 131, Short.MAX_VALUE)
                    .addComponent(jPensionLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jTaxLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jStudentLoanLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 131, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jTaxLBL, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPensionLBL, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jStudenLoanLBL, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jNIPaymentLBL, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jTaxLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTaxLBL, javax.swing.GroupLayout.DEFAULT_SIZE, 41, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPensionLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPensionLBL, javax.swing.GroupLayout.DEFAULT_SIZE, 41, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jStudentLoanLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jStudenLoanLBL, javax.swing.GroupLayout.DEFAULT_SIZE, 41, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jNIPayLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jNIPaymentLBL, javax.swing.GroupLayout.DEFAULT_SIZE, 43, Short.MAX_VALUE))
                .addContainerGap())
        );

        jPanel11.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jNetPayLabel.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jNetPayLabel.setText("Net Pay:");

        jNetPayLBL.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jNetPayLBL.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        javax.swing.GroupLayout jPanel11Layout = new javax.swing.GroupLayout(jPanel11);
        jPanel11.setLayout(jPanel11Layout);
        jPanel11Layout.setHorizontalGroup(
            jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel11Layout.createSequentialGroup()
                .addGap(13, 13, 13)
                .addComponent(jNetPayLabel)
                .addGap(32, 32, 32)
                .addComponent(jNetPayLBL, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel11Layout.setVerticalGroup(
            jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel11Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jNetPayLBL, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel11Layout.createSequentialGroup()
                        .addGap(4, 4, 4)
                        .addComponent(jNetPayLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );

        jPanel12.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jDeductionsLabel.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jDeductionsLabel.setText("Deductions:");

        jDeductionsLBL.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jDeductionsLBL.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        javax.swing.GroupLayout jPanel12Layout = new javax.swing.GroupLayout(jPanel12);
        jPanel12.setLayout(jPanel12Layout);
        jPanel12Layout.setHorizontalGroup(
            jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel12Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jDeductionsLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jDeductionsLBL, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel12Layout.setVerticalGroup(
            jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel12Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jDeductionsLBL, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel12Layout.createSequentialGroup()
                        .addGap(2, 2, 2)
                        .addComponent(jDeductionsLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 6, Short.MAX_VALUE)))
                .addContainerGap())
        );

        jPanel13.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jGrossPayLabel.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jGrossPayLabel.setText("Gross Pay:");

        jGrsPayLBL.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jGrsPayLBL.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        javax.swing.GroupLayout jPanel13Layout = new javax.swing.GroupLayout(jPanel13);
        jPanel13.setLayout(jPanel13Layout);
        jPanel13Layout.setHorizontalGroup(
            jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel13Layout.createSequentialGroup()
                .addGap(5, 5, 5)
                .addComponent(jGrossPayLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(11, 11, 11)
                .addComponent(jGrsPayLBL, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel13Layout.setVerticalGroup(
            jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel13Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jGrsPayLBL, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel13Layout.createSequentialGroup()
                        .addGap(3, 3, 3)
                        .addComponent(jGrossPayLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 5, Short.MAX_VALUE)))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jPanel3, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel6, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jDisplayDateLBL, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel11, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel12, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel13, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jPanel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel10, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel7, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jDisplayDateLBL, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jPanel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(10, 10, 10)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jPanel9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jPanel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(10, 10, 10)
                        .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(10, 10, 10)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jPanel11, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jPanel12, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(12, 12, 12)
                                .addComponent(jPanel13, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(jPanel10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void resetScript(){
       jTxtEmployeeName.setText(null);
       jTxtEmployer.setText(null);
       jTxtPhoneNumber.setText(null);
       jTxtAddress.setText(null);
       jTxtCountry.setText(null);
       jTxtPostal.setText(null);
       jTxtRefNo.setText(null);
       jTxtICW.setText(null);
       jTxtBS.setText(null);
       jTxtOT.setText(null);
       jTxtNIPayment.setText(null);
       jTxtNIPayment.setText(null);
       jTxtAreaRec.setText(null);
       jTaxLBL.setText(null);
       jPensionLBL.setText(null);
       jStudenLoanLBL.setText(null);
       jNIPaymentLBL.setText(null);
       jTaxPayLBL.setText(null);
       jPensionPayLBL.setText(null);
       jGrsPayLBL.setText(null);
       jDeductionsLBL.setText(null);
       jNetPayLBL.setText(null);
       jComboTC.setSelectedItem("A");
       jComboTP.setSelectedItem("1");
       jComboNIC.setSelectedItem("A0000");
       jPayDateChooser.setDate(null);
    }
    
    private void jTxtPhoneNumberActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTxtPhoneNumberActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTxtPhoneNumberActionPerformed

    private void jExitBTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jExitBTNActionPerformed
        System.exit(0);
    }//GEN-LAST:event_jExitBTNActionPerformed

    private void jResetBTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jResetBTNActionPerformed
       
        this.resetScript();
       
    }//GEN-LAST:event_jResetBTNActionPerformed

    private void jAddWagesBTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jAddWagesBTNActionPerformed
        double A00, A30, B40, C50, D60, E70, F80, G90;
        
        double Deduction, Pension, StudentLoad, NIPayment, TotalDeduction, NetPay, TaxablePayment, PensionablePayment, SummarizedEarnings, AllTaxes, SummarizedTaxes;
        
        InnerCity = Double.parseDouble(jTxtICW.getText());
        BasicWage = Double.parseDouble(jTxtBS.getText());
        OverTime = Double.parseDouble(jTxtOT.getText());
        Gross = InnerCity + BasicWage + OverTime;
        String GrossPay = String.format("%.2f", Gross);
        jGrsPayLBL.setText("£" + GrossPay);
        
        
        try{
            if(jComboNIC.getSelectedItem().equals("A0000")){
                
                A00 = (Gross * 9) / 100;
                Deduction = Gross - A00;
                Pension = (Deduction *12)/100;
                String TaxPaid = String.format("%.2f", A00);
                jTaxLBL.setText("£" + TaxPaid);
              
                StudentLoad = Pension + A00;
                StudentLoad = Gross - StudentLoad;
                StudentLoad = (StudentLoad * 5.7)/100;
                
                NIPayment = StudentLoad + Pension + A00;
                NIPayment = Gross - NIPayment;
                NIPayment = (NIPayment * 4.2)/100;
                
                TotalDeduction = A00 + Pension + StudentLoad + NIPayment;
                
                NetPay = Gross - TotalDeduction;
                
                SummarizedEarnings = NetPay + 0;
                

                String TaxPeriod = jComboTP.getSelectedItem().toString();
                TaxablePayment = Double.parseDouble(TaxPeriod);
                PensionablePayment = TaxablePayment * Pension;
                TaxablePayment = TaxablePayment * A00;
                
                
                
                String PensionPaid = String.format("%.2f", Pension);
                jPensionLBL.setText("£" + PensionPaid);
                
                String StudentLoanPaid = String.format("%.2f", StudentLoad);
                jStudenLoanLBL.setText("£" + StudentLoanPaid);
               
                String NIPaymentPaid = String.format("%.2f", NIPayment);
                jNIPaymentLBL.setText("£" + NIPaymentPaid);
                
                String TotalDed = String.format("%.2f", TotalDeduction);
                jDeductionsLBL.setText("£" + TotalDed);
                
                String TotalNetPay = String.format("%.2f", NetPay);
                jNetPayLBL.setText("£" + TotalNetPay);
                
                String TotalPensionPayment = String.format("%.2f", PensionablePayment);
                jPensionPayLBL.setText("£" + TotalPensionPayment);
                
                String TotalTaxablePayment = String.format("%.2f", TaxablePayment);
                jTaxPayLBL.setText("£" + TotalTaxablePayment);
                
                
                
                
                AllTaxes = StudentLoad + NIPayment + TaxablePayment;
                
                SummarizedTaxes = AllTaxes + 0;
                
                
               
            }
            
            else if(jComboNIC.getSelectedItem().equals("A3000")){
               
                A30 = 3000/12;
                
                A00 = (Gross * 9) / 100;
                Deduction = Gross - A00;
                Pension = (Deduction *12)/100;
                String TaxPaid = String.format("%.2f", A00);
                jTaxLBL.setText("£" + TaxPaid);
              
                StudentLoad = Pension + A00;
                StudentLoad = Gross - StudentLoad;
                StudentLoad = (StudentLoad * 5.7)/100;
                
                NIPayment = StudentLoad + Pension + A00;
                NIPayment = Gross - NIPayment;
                NIPayment = (NIPayment * 4.2)/100;
                
                TotalDeduction = A00 + Pension + StudentLoad + NIPayment;
                
                NetPay = Gross - TotalDeduction;
                NetPay = NetPay + A30;

                String TaxPeriod = jComboTP.getSelectedItem().toString();
                TaxablePayment = Double.parseDouble(TaxPeriod);
                PensionablePayment = TaxablePayment * Pension;
                TaxablePayment = TaxablePayment * A00;
             
                
                String PensionPaid = String.format("%.2f", Pension);
                jPensionLBL.setText("£" + PensionPaid);
                
                String StudentLoanPaid = String.format("%.2f", StudentLoad);
                jStudenLoanLBL.setText("£" + StudentLoanPaid);
               
                String NIPaymentPaid = String.format("%.2f", NIPayment);
                jNIPaymentLBL.setText("£" + NIPaymentPaid);
                
                String TotalDed = String.format("%.2f", TotalDeduction);
                jDeductionsLBL.setText("£" + TotalDed);
                
                String TotalNetPay = String.format("%.2f", NetPay);
                jNetPayLBL.setText("£" + TotalNetPay);
                
                String TotalPensionPayment = String.format("%.2f", PensionablePayment);
                jPensionPayLBL.setText("£" + TotalPensionPayment);
                
                String TotalTaxablePayment = String.format("%.2f", TaxablePayment);
                jTaxPayLBL.setText("£" + TotalTaxablePayment); 
                
            }
            
            else if(jComboNIC.getSelectedItem().equals("B4000")){
                
                B40 = 4000/12;
                
                A00 = (Gross * 9) / 100;
                Deduction = Gross - A00;
                Pension = (Deduction *12)/100;
                String TaxPaid = String.format("%.2f", A00);
                jTaxLBL.setText("£" + TaxPaid);
              
                StudentLoad = Pension + A00;
                StudentLoad = Gross - StudentLoad;
                StudentLoad = (StudentLoad * 5.7)/100;
                
                NIPayment = StudentLoad + Pension + A00;
                NIPayment = Gross - NIPayment;
                NIPayment = (NIPayment * 4.2)/100;
                
                TotalDeduction = A00 + Pension + StudentLoad + NIPayment;
                
                NetPay = Gross - TotalDeduction;
                NetPay = NetPay + B40;

                String TaxPeriod = jComboTP.getSelectedItem().toString();
                TaxablePayment = Double.parseDouble(TaxPeriod);
                PensionablePayment = TaxablePayment * Pension;
                TaxablePayment = TaxablePayment * A00;
             
                
                String PensionPaid = String.format("%.2f", Pension);
                jPensionLBL.setText("£" + PensionPaid);
                
                String StudentLoanPaid = String.format("%.2f", StudentLoad);
                jStudenLoanLBL.setText("£" + StudentLoanPaid);
               
                String NIPaymentPaid = String.format("%.2f", NIPayment);
                jNIPaymentLBL.setText("£" + NIPaymentPaid);
                
                String TotalDed = String.format("%.2f", TotalDeduction);
                jDeductionsLBL.setText("£" + TotalDed);
                
                String TotalNetPay = String.format("%.2f", NetPay);
                jNetPayLBL.setText("£" + TotalNetPay);
                
                String TotalPensionPayment = String.format("%.2f", PensionablePayment);
                jPensionPayLBL.setText("£" + TotalPensionPayment);
                
                String TotalTaxablePayment = String.format("%.2f", TaxablePayment);
                jTaxPayLBL.setText("£" + TotalTaxablePayment); 
                
            }
            
            else if(jComboNIC.getSelectedItem().equals("C5000")){
                
                C50 = 5000/12;
                
                A00 = (Gross * 9) / 100;
                Deduction = Gross - A00;
                Pension = (Deduction *12)/100;
                String TaxPaid = String.format("%.2f", A00);
                jTaxLBL.setText("£" + TaxPaid);
              
                StudentLoad = Pension + A00;
                StudentLoad = Gross - StudentLoad;
                StudentLoad = (StudentLoad * 5.7)/100;
                
                NIPayment = StudentLoad + Pension + A00;
                NIPayment = Gross - NIPayment;
                NIPayment = (NIPayment * 4.2)/100;
                
                TotalDeduction = A00 + Pension + StudentLoad + NIPayment;
                
                NetPay = Gross - TotalDeduction;
                NetPay = NetPay + C50;

                String TaxPeriod = jComboTP.getSelectedItem().toString();
                TaxablePayment = Double.parseDouble(TaxPeriod);
                PensionablePayment = TaxablePayment * Pension;
                TaxablePayment = TaxablePayment * A00;
             
                
                String PensionPaid = String.format("%.2f", Pension);
                jPensionLBL.setText("£" + PensionPaid);
                
                String StudentLoanPaid = String.format("%.2f", StudentLoad);
                jStudenLoanLBL.setText("£" + StudentLoanPaid);
               
                String NIPaymentPaid = String.format("%.2f", NIPayment);
                jNIPaymentLBL.setText("£" + NIPaymentPaid);
                
                String TotalDed = String.format("%.2f", TotalDeduction);
                jDeductionsLBL.setText("£" + TotalDed);
                
                String TotalNetPay = String.format("%.2f", NetPay);
                jNetPayLBL.setText("£" + TotalNetPay);
                
                String TotalPensionPayment = String.format("%.2f", PensionablePayment);
                jPensionPayLBL.setText("£" + TotalPensionPayment);
                
                String TotalTaxablePayment = String.format("%.2f", TaxablePayment);
                jTaxPayLBL.setText("£" + TotalTaxablePayment); 
                
            }
            
            else if(jComboNIC.getSelectedItem().equals("D6000")){
                
                D60 = 6000/12;
                
                A00 = (Gross * 9) / 100;
                Deduction = Gross - A00;
                Pension = (Deduction *12)/100;
                String TaxPaid = String.format("%.2f", A00);
                jTaxLBL.setText("£" + TaxPaid);
              
                StudentLoad = Pension + A00;
                StudentLoad = Gross - StudentLoad;
                StudentLoad = (StudentLoad * 5.7)/100;
                
                NIPayment = StudentLoad + Pension + A00;
                NIPayment = Gross - NIPayment;
                NIPayment = (NIPayment * 4.2)/100;
                
                TotalDeduction = A00 + Pension + StudentLoad + NIPayment;
                
                NetPay = Gross - TotalDeduction;
                NetPay = NetPay + D60;

                String TaxPeriod = jComboTP.getSelectedItem().toString();
                TaxablePayment = Double.parseDouble(TaxPeriod);
                PensionablePayment = TaxablePayment * Pension;
                TaxablePayment = TaxablePayment * A00;
             
                
                String PensionPaid = String.format("%.2f", Pension);
                jPensionLBL.setText("£" + PensionPaid);
                
                String StudentLoanPaid = String.format("%.2f", StudentLoad);
                jStudenLoanLBL.setText("£" + StudentLoanPaid);
               
                String NIPaymentPaid = String.format("%.2f", NIPayment);
                jNIPaymentLBL.setText("£" + NIPaymentPaid);
                
                String TotalDed = String.format("%.2f", TotalDeduction);
                jDeductionsLBL.setText("£" + TotalDed);
                
                String TotalNetPay = String.format("%.2f", NetPay);
                jNetPayLBL.setText("£" + TotalNetPay);
                
                String TotalPensionPayment = String.format("%.2f", PensionablePayment);
                jPensionPayLBL.setText("£" + TotalPensionPayment);
                
                String TotalTaxablePayment = String.format("%.2f", TaxablePayment);
                jTaxPayLBL.setText("£" + TotalTaxablePayment); 
                
            }
            
            else if(jComboNIC.getSelectedItem().equals("E7000")){
                
                E70 = 7000/12;
                
                A00 = (Gross * 9) / 100;
                Deduction = Gross - A00;
                Pension = (Deduction *12)/100;
                String TaxPaid = String.format("%.2f", A00);
                jTaxLBL.setText("£" + TaxPaid);
              
                StudentLoad = Pension + A00;
                StudentLoad = Gross - StudentLoad;
                StudentLoad = (StudentLoad * 5.7)/100;
                
                NIPayment = StudentLoad + Pension + A00;
                NIPayment = Gross - NIPayment;
                NIPayment = (NIPayment * 4.2)/100;
                
                TotalDeduction = A00 + Pension + StudentLoad + NIPayment;
                
                NetPay = Gross - TotalDeduction;
                NetPay = NetPay + E70;

                String TaxPeriod = jComboTP.getSelectedItem().toString();
                TaxablePayment = Double.parseDouble(TaxPeriod);
                PensionablePayment = TaxablePayment * Pension;
                TaxablePayment = TaxablePayment * A00;
             
                
                String PensionPaid = String.format("%.2f", Pension);
                jPensionLBL.setText("£" + PensionPaid);
                
                String StudentLoanPaid = String.format("%.2f", StudentLoad);
                jStudenLoanLBL.setText("£" + StudentLoanPaid);
               
                String NIPaymentPaid = String.format("%.2f", NIPayment);
                jNIPaymentLBL.setText("£" + NIPaymentPaid);
                
                String TotalDed = String.format("%.2f", TotalDeduction);
                jDeductionsLBL.setText("£" + TotalDed);
                
                String TotalNetPay = String.format("%.2f", NetPay);
                jNetPayLBL.setText("£" + TotalNetPay);
                
                String TotalPensionPayment = String.format("%.2f", PensionablePayment);
                jPensionPayLBL.setText("£" + TotalPensionPayment);
                
                String TotalTaxablePayment = String.format("%.2f", TaxablePayment);
                jTaxPayLBL.setText("£" + TotalTaxablePayment); 
                
            }
            
            else if(jComboNIC.getSelectedItem().equals("F8000")){
                
                F80 = 8000/12;
                
                A00 = (Gross * 9) / 100;
                Deduction = Gross - A00;
                Pension = (Deduction *12)/100;
                String TaxPaid = String.format("%.2f", A00);
                jTaxLBL.setText("£" + TaxPaid);
              
                StudentLoad = Pension + A00;
                StudentLoad = Gross - StudentLoad;
                StudentLoad = (StudentLoad * 5.7)/100;
                
                NIPayment = StudentLoad + Pension + A00;
                NIPayment = Gross - NIPayment;
                NIPayment = (NIPayment * 4.2)/100;
                
                TotalDeduction = A00 + Pension + StudentLoad + NIPayment;
                
                NetPay = Gross - TotalDeduction;
                NetPay = NetPay + F80;

                String TaxPeriod = jComboTP.getSelectedItem().toString();
                TaxablePayment = Double.parseDouble(TaxPeriod);
                PensionablePayment = TaxablePayment * Pension;
                TaxablePayment = TaxablePayment * A00;
             
                
                String PensionPaid = String.format("%.2f", Pension);
                jPensionLBL.setText("£" + PensionPaid);
                
                String StudentLoanPaid = String.format("%.2f", StudentLoad);
                jStudenLoanLBL.setText("£" + StudentLoanPaid);
               
                String NIPaymentPaid = String.format("%.2f", NIPayment);
                jNIPaymentLBL.setText("£" + NIPaymentPaid);
                
                String TotalDed = String.format("%.2f", TotalDeduction);
                jDeductionsLBL.setText("£" + TotalDed);
                
                String TotalNetPay = String.format("%.2f", NetPay);
                jNetPayLBL.setText("£" + TotalNetPay);
                
                String TotalPensionPayment = String.format("%.2f", PensionablePayment);
                jPensionPayLBL.setText("£" + TotalPensionPayment);
                
                String TotalTaxablePayment = String.format("%.2f", TaxablePayment);
                jTaxPayLBL.setText("£" + TotalTaxablePayment); 
                
            }
            
            else if(jComboNIC.getSelectedItem().equals("G9000")){
                
                G90 = 9000/12;
                
                A00 = (Gross * 9) / 100;
                Deduction = Gross - A00;
                Pension = (Deduction *12)/100;
                String TaxPaid = String.format("%.2f", A00);
                jTaxLBL.setText("£" + TaxPaid);
              
                StudentLoad = Pension + A00;
                StudentLoad = Gross - StudentLoad;
                StudentLoad = (StudentLoad * 5.7)/100;
                
                NIPayment = StudentLoad + Pension + A00;
                NIPayment = Gross - NIPayment;
                NIPayment = (NIPayment * 4.2)/100;
                
                TotalDeduction = A00 + Pension + StudentLoad + NIPayment;
                
                NetPay = Gross - TotalDeduction;
                NetPay = NetPay + G90;

                String TaxPeriod = jComboTP.getSelectedItem().toString();
                TaxablePayment = Double.parseDouble(TaxPeriod);
                PensionablePayment = TaxablePayment * Pension;
                TaxablePayment = TaxablePayment * A00;
             
                
                String PensionPaid = String.format("%.2f", Pension);
                jPensionLBL.setText("£" + PensionPaid);
                
                String StudentLoanPaid = String.format("%.2f", StudentLoad);
                jStudenLoanLBL.setText("£" + StudentLoanPaid);
               
                String NIPaymentPaid = String.format("%.2f", NIPayment);
                jNIPaymentLBL.setText("£" + NIPaymentPaid);
                
                String TotalDed = String.format("%.2f", TotalDeduction);
                jDeductionsLBL.setText("£" + TotalDed);
                
                String TotalNetPay = String.format("%.2f", NetPay);
                jNetPayLBL.setText("£" + TotalNetPay);
                
                String TotalPensionPayment = String.format("%.2f", PensionablePayment);
                jPensionPayLBL.setText("£" + TotalPensionPayment);
                
                String TotalTaxablePayment = String.format("%.2f", TaxablePayment);
                jTaxPayLBL.setText("£" + TotalTaxablePayment); 
                
            }
            
        }
        catch (NumberFormatException e){
            JOptionPane.showMessageDialog(null, "Enter a Valid Number", "Only Numbers", JOptionPane.INFORMATION_MESSAGE);
        }
    }//GEN-LAST:event_jAddWagesBTNActionPerformed

    private void jNewEmployeeBTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jNewEmployeeBTNActionPerformed
       Employee_Registration empre = new Employee_Registration();
      
        empre.setVisible(true);
    }//GEN-LAST:event_jNewEmployeeBTNActionPerformed

    private void jPayReferenceBTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jPayReferenceBTNActionPerformed
        
        DateFormat df = new SimpleDateFormat("yyyy-MM-dd");
        
        String name = jTxtEmployeeName.getText();
        String address = jTxtAddress.getText();
        String country = jTxtCountry.getText();
        String postal_code = jTxtPostal.getText();
        String ref_no = jTxtRefNo.getText();
        String employer_name = jTxtEmployer.getText();
        String phone_number = jTxtPhoneNumber.getText();
        String ni_payment = jTxtNIPayment.getText();
        String net_pay = jNetPayLBL.getText();
        String date = df.format(jPayDateChooser.getDate());
        String comment = jTxtAreaRec.getText();
        
        
        
        
        try{
            
            Class.forName("com.mysql.jdbc.Driver");
            con_user_data = DriverManager.getConnection("jdbc:mysql://localhost:3306/paymentsys", "root", "");
            pstmt = con_user_data.prepareStatement("insert into user_data_uk values (?, ?, ? , ? , ?, ?, ?, ?, ?, ?, ?)");
            
            pstmt.setString(1, name);
            pstmt.setString(2, address);
            pstmt.setString(3, country);
            pstmt.setString(4, postal_code);
            pstmt.setString(5, ref_no);
            pstmt.setString(6, employer_name);
            pstmt.setString(7, phone_number);
            pstmt.setString(8, ni_payment);
            pstmt.setString(9, net_pay);
            pstmt.setString(10, date);
            pstmt.setString(11, comment);
            
            int i = pstmt.executeUpdate();
            
            if(i>0){
                JOptionPane.showMessageDialog(null, "Data is Saved");
            }
            else{
            JOptionPane.showMessageDialog(null, "Data is Not Saved");
            }
            
            this.resetScript();
            
        }
        catch(HeadlessException | ClassNotFoundException | SQLException e){
            JOptionPane.showMessageDialog(null, e);
        }
    }//GEN-LAST:event_jPayReferenceBTNActionPerformed

    private void jPayReferenceBTNKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jPayReferenceBTNKeyReleased
        this.resetScript();
    }//GEN-LAST:event_jPayReferenceBTNKeyReleased
    
    
    @SuppressWarnings("deprecation")
    private void fillCombo(){
        
        try{
            
            String sql = "select * from employee_list";
            con_emp_list = DriverManager.getConnection("jdbc:mysql://localhost:3306/paymentsys", "root", "");
            prepstat = con_emp_list.prepareStatement(sql);
            resSet = prepstat.executeQuery();
            while(resSet.next()){
               
                String name = resSet.getString("emp_name");
                jRegEmployeeCB.addItem(name);
              
             
            }
        }
        
        catch(SQLException e){
            
            JOptionPane.showMessageDialog(null, e);
            
        }
    }

    
    private void jRegEmployeeCBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRegEmployeeCBActionPerformed
        
    }//GEN-LAST:event_jRegEmployeeCBActionPerformed

    private void jDataSetBTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jDataSetBTNActionPerformed
            String tmp = (String) jRegEmployeeCB.getSelectedItem();
            String sql = "select * from employee_list where emp_name = ?";
            
            
        try{
           
            con_emp_list = DriverManager.getConnection("jdbc:mysql://localhost:3306/paymentsys", "root", "");
            prepstat = con_emp_list.prepareStatement(sql);
            prepstat.setString(1, tmp);
            resSet = prepstat.executeQuery();
            
            if(resSet.next()){
                
                String empname = resSet.getString("emp_name");
                jTxtEmployeeName.setText(empname);
                
                String empaddress = resSet.getString("emp_address");
                jTxtAddress.setText(empaddress);
                
                String empcountry = resSet.getString("emp_country");
                jTxtCountry.setText(empcountry);
                
                String emppostal= resSet.getString("emp_postal_code");
                jTxtPostal.setText(emppostal);
                
                String emprefno = resSet.getString("emp_ref_no");
                jTxtRefNo.setText(emprefno);
                
                String empemployer = resSet.getString("emp_employer");
                jTxtEmployer.setText(empemployer);
                
                String empphone = resSet.getString("emp_phone_number");
                jTxtPhoneNumber.setText(empphone);
                
            }
        }
        
        catch(SQLException e){
            
            JOptionPane.showMessageDialog(null, e);
            
        }       
    }//GEN-LAST:event_jDataSetBTNActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Paymentsystem.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        
        //</editor-fold>
        //</editor-fold>
        
        

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Paymentsystem().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jAddWagesBTN;
    private javax.swing.JLabel jAdressLabel;
    private javax.swing.JLabel jBasicSalaryLabel;
    private javax.swing.JComboBox<String> jComboNIC;
    private javax.swing.JComboBox<String> jComboTC;
    private javax.swing.JComboBox<String> jComboTP;
    private javax.swing.JLabel jCountryLabel;
    private javax.swing.JButton jDataSetBTN;
    private javax.swing.JLabel jDeductionsLBL;
    private javax.swing.JLabel jDeductionsLabel;
    private javax.swing.JPanel jDisplayDateLBL;
    private javax.swing.JLabel jEmployeeNameLabel;
    private javax.swing.JLabel jEmployeeNameLabel3;
    private javax.swing.JLabel jEmpoyerNameLabel;
    private javax.swing.JButton jExitBTN;
    private javax.swing.JLabel jGrossPayLabel;
    private javax.swing.JLabel jGrsPayLBL;
    private javax.swing.JLabel jInnerCityLabel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jNICodeLabel;
    private javax.swing.JLabel jNIPayLabel;
    private javax.swing.JLabel jNIPaymentLBL;
    private javax.swing.JLabel jNIPaymentLabel;
    private javax.swing.JLabel jNetPayLBL;
    private javax.swing.JLabel jNetPayLabel;
    private javax.swing.JButton jNewEmployeeBTN;
    private javax.swing.JLabel jOverTimeLabel;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel11;
    private javax.swing.JPanel jPanel12;
    private javax.swing.JPanel jPanel13;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private com.toedter.calendar.JDateChooser jPayDateChooser;
    private javax.swing.JLabel jPayDateLabel;
    private javax.swing.JButton jPayReferenceBTN;
    private javax.swing.JLabel jPensionLBL;
    private javax.swing.JLabel jPensionLabel;
    private javax.swing.JLabel jPensionPayLBL;
    private javax.swing.JLabel jPensionablePayLabel;
    private javax.swing.JLabel jPhoneNumberLabel;
    private javax.swing.JLabel jPostalLabel;
    private javax.swing.JLabel jRefNoLabel;
    private javax.swing.JComboBox<String> jRegEmployeeCB;
    private javax.swing.JLabel jRegEmployeeLBL;
    private javax.swing.JButton jResetBTN;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel jStudenLoanLBL;
    private javax.swing.JLabel jStudentLoanLabel;
    private javax.swing.JLabel jTaxCodeLabel;
    private javax.swing.JLabel jTaxLBL;
    private javax.swing.JLabel jTaxLabel;
    private javax.swing.JLabel jTaxPayLBL;
    private javax.swing.JLabel jTaxPeriodLabel;
    private javax.swing.JLabel jTaxablePayLabel;
    private javax.swing.JTextField jTxtAddress;
    private javax.swing.JTextArea jTxtAreaRec;
    private javax.swing.JTextField jTxtBS;
    private javax.swing.JTextField jTxtCountry;
    private javax.swing.JTextField jTxtEmployeeName;
    private javax.swing.JTextField jTxtEmployer;
    private javax.swing.JTextField jTxtICW;
    private javax.swing.JTextField jTxtNIPayment;
    private javax.swing.JTextField jTxtOT;
    private javax.swing.JTextField jTxtPhoneNumber;
    private javax.swing.JTextField jTxtPostal;
    private javax.swing.JTextField jTxtRefNo;
    // End of variables declaration//GEN-END:variables
}
